language: ruby

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE chitter_app_test;' -U postgres
  - psql  -U postgres chitter_app_test < db/migrations/01_create_peeps_table.sql

script:
  - bundle exec rspec
